#!/usr/bin/env python3
"""
Code Audit: Critical Issues Found Before Testing
Report generated before bot startup
"""

print("=" * 80)
print("🔍 CRITICAL CODE AUDIT - Issues Found")
print("=" * 80)
print()

issues = []

# ISSUE 1: Bot creates wrong tables
print("❌ ISSUE 1: BOT CREATES WRONG DATABASE TABLES")
print("-" * 80)
print("Location: bot/ultimate_bot.py, line ~1888-1945")
print()
print("Problem:")
print("  The bot's initialize_database() creates its OWN tables:")
print("    • sessions (different schema than recreate_database.py)")
print("    • player_links")
print("    • player_stats (WRONG - should use player_comprehensive_stats)")
print()
print("Impact:")
print("  ❌ Bot queries player_comprehensive_stats")
print("  ❌ But bot creates player_stats table")
print("  ❌ These are DIFFERENT tables!")
print()
print("Evidence:")
print("  • Bot command queries: SELECT FROM player_comprehensive_stats")
print("  • Bot init creates: CREATE TABLE player_stats")
print("  • Import script writes to: player_comprehensive_stats")
print()
print("Result:")
print("  Bot will work because player_comprehensive_stats already exists")
print("  from recreate_database.py, but bot's initialize_database()")
print("  is creating unnecessary duplicate table structure!")
print()
issues.append("Bot creates wrong/duplicate tables")

# ISSUE 2: Bot queries use wrong table names in some places
print("❌ ISSUE 2: INCONSISTENT TABLE REFERENCES")
print("-" * 80)
print("Location: bot/ultimate_bot.py, multiple commands")
print()
print("Problem:")
print("  Some bot commands query 'sessions' table")
print("  But recreate_database.py schema may differ from bot schema")
print()
print("Check needed:")
print("  1. Does sessions table match between:")
print("     - recreate_database.py")
print("     - bot/ultimate_bot.py initialize_database()")
print()
print("  2. Does player_links table exist in recreate_database.py?")
print("     - Bot creates it in initialize_database()")
print("     - Used by !link and !unlink commands")
print()
issues.append("Inconsistent table schemas")

# ISSUE 3: SQL injection risk (minor)
print("⚠️  ISSUE 3: POTENTIAL SQL INJECTION (LOW RISK)")
print("-" * 80)
print("Location: bot/ultimate_bot.py, line ~747")
print()
print("Problem:")
print("  Dynamic SQL with f-string:")
print("  query = f'''")
print("      SELECT ... WHERE session_id IN ({session_ids_str})")
print("  '''")
print()
print("Why it's low risk:")
print("  session_ids_str is built from internal IDs, not user input")
print()
print("Best practice:")
print("  Still safer to use proper parameterized queries")
print()
issues.append("SQL injection risk (low)")

# ISSUE 4: Missing error handling
print("⚠️  ISSUE 4: MISSING NULL CHECKS")
print("-" * 80)
print("Location: Multiple commands")
print()
print("Problem:")
print("  Some queries don't check for None/empty results before using")
print()
print("Examples:")
print("  • !last_session: top_players could be empty")
print("  • !stats: weapon_overall could be None")
print()
print("Impact:")
print("  Could cause crashes on empty database or missing data")
print()
issues.append("Missing null checks")

# ISSUE 5: Database connection in __init__
print("✅ ISSUE 5: DATABASE CONNECTION HANDLING")
print("-" * 80)
print("Location: bot/ultimate_bot.py __init__")
print()
print("Status: ACTUALLY OK")
print("  Bot uses aiosqlite.connect() in each command")
print("  Properly opens/closes connections with 'async with'")
print("  No connection pooling, but acceptable for bot usage")
print()

# ISSUE 6: Bot table schema mismatch
print("❌ ISSUE 6: SCHEMA MISMATCH BETWEEN BOT AND IMPORT")
print("-" * 80)
print()
print("recreate_database.py creates:")
print("  • sessions (session_date, map_name, round_number, time_limit, actual_time)")
print("  • player_comprehensive_stats (49 columns)")
print("  • weapon_comprehensive_stats")
print()
print("bot/ultimate_bot.py creates:")
print("  • sessions (start_time, end_time, date, map_name, status, total_rounds)")
print("  • player_stats (different schema)")
print("  • player_links")
print()
print("Critical:")
print("  These are COMPLETELY DIFFERENT schemas!")
print("  Bot will use recreate_database.py tables (already exist)")
print("  But initialize_database() creates conflicting structure")
print()
print("Solution:")
print("  Bot should NOT create tables!")
print("  Tables already created by recreate_database.py")
print("  Bot should only check if tables exist")
print()
issues.append("Schema mismatch")

print()
print("=" * 80)
print("SUMMARY")
print("=" * 80)
print(f"Total issues found: {len(issues)}")
for i, issue in enumerate(issues, 1):
    print(f"  {i}. {issue}")
print()

print("=" * 80)
print("RECOMMENDED ACTIONS BEFORE STARTING BOT")
print("=" * 80)
print()
print("1. ⚠️  CRITICAL: Fix bot's initialize_database()")
print("   • Remove CREATE TABLE statements")
print("   • Just verify tables exist")
print("   • Don't recreate different schema")
print()
print("2. ✅ Add player_links to recreate_database.py")
print("   • Bot needs this for !link and !unlink")
print("   • Should be in main schema, not bot-created")
print()
print("3. ⚠️  Add NULL checks in commands")
print("   • Check if queries return empty results")
print("   • Handle gracefully")
print()
print("4. ✅ Test on empty database first")
print("   • See what errors appear")
print("   • Fix before loading all data")
print()
print("=" * 80)
print()
print("🤔 DECISION NEEDED:")
print("   A) Fix these issues now (recommended)")
print("   B) Test as-is and fix errors as they appear")
print("   C) Use existing data and see what breaks")
print()
print("Recommendation: Option A - Fix critical issues now")
print("=" * 80)
