#!/bin/bash
################################################################################
# ET:Legacy Discord Bot - VPS Installation Script
# 
# ⚠️  DEPRECATED - This script is deprecated in favor of install.sh
# Please use: sudo ./install.sh --vps --interactive
# See INSTALL_SCRIPTS_DEPRECATED.md for details
################################################################################

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚠️  DEPRECATION NOTICE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "This script (vps_setup.sh) is DEPRECATED."
echo ""
echo "Please use the unified installation script instead:"
echo "  sudo ./install.sh --vps --interactive"
echo ""
echo "The new script has all the same features plus more flexibility."
echo "See INSTALL_SCRIPTS_DEPRECATED.md for the migration guide."
echo ""
read -p "Continue with deprecated script anyway? [y/N] " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Installation cancelled. Please use: sudo ./install.sh --vps --interactive"
    exit 1
fi
echo ""

set -e  # Exit on any error

echo "================================="
echo "ET:Legacy Bot VPS Setup"
echo "================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Get the directory where the script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

echo -e "${GREEN}📁 Working directory: $SCRIPT_DIR${NC}"
echo ""

################################################################################
# Step 1: Install System Dependencies
################################################################################
echo -e "${YELLOW}Step 1: Installing system dependencies...${NC}"
sudo apt-get update
sudo apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    postgresql \
    postgresql-contrib \
    git

echo -e "${GREEN}✅ System dependencies installed${NC}"
echo ""

################################################################################
# Step 2: Set up PostgreSQL Database
################################################################################
echo -e "${YELLOW}Step 2: Setting up PostgreSQL database...${NC}"

# Prompt for database password
read -sp "Enter password for PostgreSQL user 'etlegacy_user': " DB_PASSWORD
echo ""
read -sp "Confirm password: " DB_PASSWORD_CONFIRM
echo ""

if [ "$DB_PASSWORD" != "$DB_PASSWORD_CONFIRM" ]; then
    echo -e "${RED}❌ Passwords don't match. Exiting.${NC}"
    exit 1
fi

# Create database and user
# Escape single quotes for PostgreSQL (prevents SQL injection)
DB_PASSWORD_ESCAPED="${DB_PASSWORD//\'/\'\'}"

sudo -u postgres psql << EOF
-- Create database
CREATE DATABASE etlegacy;

-- Create user
CREATE USER etlegacy_user WITH PASSWORD '$DB_PASSWORD_ESCAPED';

-- Grant privileges
GRANT ALL PRIVILEGES ON DATABASE etlegacy TO etlegacy_user;

-- Additional permissions for the user on the database
\c etlegacy
GRANT ALL ON SCHEMA public TO etlegacy_user;

EOF

echo -e "${GREEN}✅ PostgreSQL database 'etlegacy' created${NC}"
echo -e "${GREEN}✅ User 'etlegacy_user' created with privileges${NC}"
echo ""

################################################################################
# Step 3: Create Python Virtual Environment
################################################################################
echo -e "${YELLOW}Step 3: Creating Python virtual environment...${NC}"

if [ -d ".venv" ]; then
    echo -e "${YELLOW}⚠️  Virtual environment already exists, skipping...${NC}"
else
    python3 -m venv .venv
    echo -e "${GREEN}✅ Virtual environment created${NC}"
fi

# Activate virtual environment
source .venv/bin/activate

echo -e "${GREEN}✅ Virtual environment activated${NC}"
echo ""

################################################################################
# Step 4: Install Python Dependencies
################################################################################
echo -e "${YELLOW}Step 4: Installing Python packages...${NC}"

pip install --upgrade pip
pip install -r requirements.txt

echo -e "${GREEN}✅ Python packages installed${NC}"
echo ""

################################################################################
# Step 5: Create .env Configuration File
################################################################################
echo -e "${YELLOW}Step 5: Creating .env configuration file...${NC}"

# Prompt for Discord token
read -p "Enter your Discord Bot Token: " DISCORD_TOKEN
read -p "Enter your Discord Guild ID: " GUILD_ID
read -p "Enter stats channel ID (or press Enter to skip): " STATS_CHANNEL

# Create .env file
cat > .env << EOF
# ET:Legacy Discord Bot Configuration
# Auto-generated by vps_setup.sh

# ========== DATABASE CONFIGURATION ==========
DATABASE_TYPE=postgresql

# PostgreSQL Configuration
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_DATABASE=etlegacy
POSTGRES_USER=etlegacy_user
POSTGRES_PASSWORD=$DB_PASSWORD
POSTGRES_MIN_POOL=10
POSTGRES_MAX_POOL=30

# SQLite Configuration (not used in production)
SQLITE_DB_PATH=bot/etlegacy_production.db

# ========== DISCORD CONFIGURATION ==========
DISCORD_BOT_TOKEN=$DISCORD_TOKEN
GUILD_ID=$GUILD_ID
STATS_CHANNEL_ID=$STATS_CHANNEL

# ========== STATS FILE CONFIGURATION ==========
STATS_DIRECTORY=local_stats
BACKUP_DIRECTORY=processed_stats

# ========== AUTOMATION SETTINGS ==========
AUTOMATION_ENABLED=false
LOG_LEVEL=INFO
EOF

chmod 600 .env  # Secure the .env file

echo -e "${GREEN}✅ .env file created and secured (chmod 600)${NC}"
echo ""

################################################################################
# Step 6: Initialize Database Schema
################################################################################
echo -e "${YELLOW}Step 6: Initializing database schema...${NC}"

python3 postgresql_database_manager.py << EOF
1
EOF

echo -e "${GREEN}✅ Database schema initialized${NC}"
echo ""

################################################################################
# Step 7: Create Systemd Service (Optional)
################################################################################
echo -e "${YELLOW}Step 7: Create systemd service? (y/n)${NC}"
read -p "Answer: " CREATE_SERVICE

if [ "$CREATE_SERVICE" = "y" ] || [ "$CREATE_SERVICE" = "Y" ]; then
    SERVICE_FILE="/etc/systemd/system/etlegacy-bot.service"
    
    sudo tee $SERVICE_FILE > /dev/null << EOF
[Unit]
Description=ET:Legacy Discord Bot
After=network.target postgresql.service

[Service]
Type=simple
User=$USER
WorkingDirectory=$SCRIPT_DIR
Environment="PATH=$SCRIPT_DIR/.venv/bin"
ExecStart=$SCRIPT_DIR/.venv/bin/python $SCRIPT_DIR/bot/ultimate_bot.py
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

    sudo systemctl daemon-reload
    sudo systemctl enable etlegacy-bot.service
    
    echo -e "${GREEN}✅ Systemd service created: etlegacy-bot.service${NC}"
    echo -e "${GREEN}   Start with: sudo systemctl start etlegacy-bot${NC}"
    echo -e "${GREEN}   Status:     sudo systemctl status etlegacy-bot${NC}"
    echo -e "${GREEN}   Logs:       sudo journalctl -u etlegacy-bot -f${NC}"
else
    echo -e "${YELLOW}⏭️  Skipping systemd service creation${NC}"
fi

echo ""

################################################################################
# Step 8: Final Instructions
################################################################################
echo -e "${GREEN}=================================${NC}"
echo -e "${GREEN}✅ Installation Complete!${NC}"
echo -e "${GREEN}=================================${NC}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo ""

if [ "$CREATE_SERVICE" = "y" ] || [ "$CREATE_SERVICE" = "Y" ]; then
    echo -e "  1. Start the bot:"
    echo -e "     ${GREEN}sudo systemctl start etlegacy-bot${NC}"
    echo ""
    echo -e "  2. Check status:"
    echo -e "     ${GREEN}sudo systemctl status etlegacy-bot${NC}"
    echo ""
    echo -e "  3. View logs:"
    echo -e "     ${GREEN}sudo journalctl -u etlegacy-bot -f${NC}"
else
    echo -e "  1. Activate virtual environment:"
    echo -e "     ${GREEN}source .venv/bin/activate${NC}"
    echo ""
    echo -e "  2. Start the bot manually:"
    echo -e "     ${GREEN}python3 bot/ultimate_bot.py${NC}"
    echo ""
    echo -e "  3. Or run in background with screen:"
    echo -e "     ${GREEN}screen -S etlegacy-bot${NC}"
    echo -e "     ${GREEN}python3 bot/ultimate_bot.py${NC}"
    echo -e "     ${GREEN}# Press Ctrl+A then D to detach${NC}"
fi

echo ""
echo -e "${YELLOW}Important files:${NC}"
echo -e "  Configuration:  .env"
echo -e "  Database:       PostgreSQL (etlegacy database)"
echo -e "  Stats files:    local_stats/"
echo -e "  Logs:           logs/"
echo ""
echo -e "${GREEN}🎉 Happy gaming!${NC}"
