name: Bug report
description: Report a reproducible bug
title: "fix: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What broke and what did you expect?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Exact steps, commands, and inputs.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version/commit
      description: Tag or commit SHA
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      render: shell
