-- c0rnp0rn3.lua Placeholder
-- This is the ET:Legacy Lua script that generates stats files
-- 
-- IMPORTANT: Replace this file with the actual c0rnp0rn3.lua from your server
-- when you get home!
--
-- This script:
-- - Runs on ET:Legacy game server
-- - Generates stats files in the format: YYYY-MM-DD-HHMMSS-mapname-round-X.txt
-- - Contains player stats, weapon stats, and objective stats
-- - Required for the Discord bot to parse and import stats
--
-- File should be located: server/c0rnp0rn3.lua
-- (or server/c0rnp0rn7.lua - whichever naming you use)
--
-- TODO: Upload actual lua script when available
