#!/usr/bin/env node
// Generates docs/ROUTE_MAP_2026-07.md from website/js/route-registry.js — the
// single source of truth for which frontend (legacy JS vs. React/modern)
// serves each hash route. Re-run after editing route-registry.js so the doc
// never drifts from the code the way a hand-written table would.
//
// Usage: node scripts/generate_route_map.mjs > docs/ROUTE_MAP_2026-07.md

import { readFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import { listRouteDefinitions, VIEW_MODE } from '../website/js/route-registry.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const legacyDir = path.join(repoRoot, 'website/js');
const pagesDir = path.join(repoRoot, 'website/frontend/src/pages');

// Build an index of exported function name -> defining file, e.g.
// "loadSessionsView" -> "sessions.js", by scanning every legacy JS file for
// `export function X(` / `export async function X(`. This is how
// route-registry.js's `load: ({ legacy }) => legacy.loadXView()` callbacks
// actually resolve at runtime, so it's the only accurate way to answer
// "which file serves this route" — filename-guessing gets it wrong (e.g.
// 'admin' -> admin-panel.js, 'leaderboards' -> leaderboard.js singular).
function buildLegacyFunctionIndex() {
    const index = new Map();
    const exportRe = /export\s+(?:async\s+)?function\s+(\w+)\s*\(/g;
    for (const file of readdirSync(legacyDir)) {
        if (!file.endsWith('.js') || file === 'route-registry.js') continue;
        const text = readFileSync(path.join(legacyDir, file), 'utf8');
        let match;
        while ((match = exportRe.exec(text)) !== null) {
            if (!index.has(match[1])) {
                index.set(match[1], file);
            }
        }
    }
    return index;
}

function legacyFileFor(def, legacyIndex) {
    const source = def.load.toString();
    const calls = [...source.matchAll(/legacy\.(\w+)\(/g)].map((m) => m[1]);
    const files = new Set(calls.map((name) => legacyIndex.get(name)).filter(Boolean));
    if (files.size === 0) {
        return calls.length ? `unresolved (calls: ${calls.join(', ')})` : '(no legacy.* call in load())';
    }
    return [...files].join(', ');
}

function modernFileFor(viewId) {
    const pascal = viewId
        .split('-')
        .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
        .join('');
    const candidates = readdirSync(pagesDir).filter((f) => f.endsWith('.tsx'));
    const exact = candidates.find((f) => f === `${pascal}.tsx`);
    return exact ? `website/frontend/src/pages/${exact}` : `website/frontend/src/pages/ (no exact ${pascal}.tsx — check manually)`;
}

const legacyIndex = buildLegacyFunctionIndex();
const definitions = listRouteDefinitions();
const rows = Object.entries(definitions)
    .map(([routeKey, def]) => ({
        routeKey,
        viewId: def.viewId,
        mode: def.mode,
        hashExample: (() => {
            try {
                return def.buildHash({}) || '(needs params)';
            } catch {
                return '(needs params)';
            }
        })(),
        file: def.mode === VIEW_MODE.MODERN ? modernFileFor(def.viewId) : legacyFileFor(def, legacyIndex),
    }))
    .sort((a, b) => a.routeKey.localeCompare(b.routeKey));

const lines = [];
lines.push('# Route Map — React vs. legacy JS');
lines.push('');
lines.push('**Generated by `scripts/generate_route_map.mjs` from `website/js/route-registry.js`');
lines.push('— do not hand-edit, re-run the generator after route-registry.js or the pages it');
lines.push('references change.**');
lines.push('');
lines.push(`Generated: ${new Date().toISOString().slice(0, 10)}`);
lines.push('');
lines.push('| Route key | Hash example | Implementation | Serving file |');
lines.push('|---|---|---|---|');
for (const row of rows) {
    const impl = row.mode === VIEW_MODE.MODERN ? 'React (modern)' : 'Legacy JS';
    lines.push(`| \`${row.routeKey}\` | \`${row.hashExample}\` | ${impl} | ${row.file} |`);
}
lines.push('');
lines.push(`Total: ${rows.length} routes — ${rows.filter((r) => r.mode === VIEW_MODE.MODERN).length} React, ${rows.filter((r) => r.mode === VIEW_MODE.LEGACY).length} legacy.`);
lines.push('');
lines.push('"Serving file" for legacy routes is resolved by scanning every `website/js/*.js`');
lines.push('file for the `export function <name>(` that matches the `legacy.<name>()` call in');
lines.push('the route\'s `load()` — not a filename guess. Modern (React) routes mount through');
lines.push('`website/frontend/src/route-host.tsx`; the page file is matched by PascalCase');
lines.push('convention against `website/frontend/src/pages/*.tsx`.');

console.log(lines.join('\n'));
