"""Read-only ET map geometry primitives.

The package deliberately stops at asset discovery, BSP decoding, and typed
entity extraction. Trace-mask policy, dynamic entity state, and all derived
metrics belong to later Spider Web workstreams and must not be inferred here.
"""

from website.backend.map_geometry.bsp import (
    BSP_MAGIC,
    BSP_VERSION,
    BspBrush,
    BspBrushSide,
    BspDrawVertex,
    BspFile,
    BspFormatError,
    BspLeaf,
    BspLump,
    BspModel,
    BspNode,
    BspPlane,
    BspShader,
    BspSurface,
    LumpType,
    SurfaceType,
    UnsupportedBspError,
    parse_bsp,
    parse_bsp_file,
    parse_entities,
)
from website.backend.map_geometry.entities import (
    Bounds3D,
    CollisionBrushEntity,
    ConvexBrushVolume,
    EntityExtractionError,
    InlineModelGeometry,
    MapEntityCatalog,
    ObjectiveGeometrySource,
    ObjectiveMarker,
    ObjectiveVolume,
    SpawnPoint,
    VolumePlane,
    entity_catalog_manifest,
    extract_entity_catalog,
)
from website.backend.map_geometry.pk3_index import (
    AssetContentChangedError,
    GeometryResolution,
    MapAssetKind,
    MapAssetProvider,
    MapAssetResolution,
    Pk3GeometryIndex,
    Pk3IndexError,
)

__all__ = [
    "AssetContentChangedError",
    "BSP_MAGIC",
    "BSP_VERSION",
    "BspBrush",
    "BspBrushSide",
    "BspDrawVertex",
    "BspFile",
    "BspFormatError",
    "BspLeaf",
    "BspLump",
    "BspModel",
    "BspNode",
    "BspPlane",
    "BspShader",
    "BspSurface",
    "Bounds3D",
    "CollisionBrushEntity",
    "ConvexBrushVolume",
    "EntityExtractionError",
    "GeometryResolution",
    "InlineModelGeometry",
    "LumpType",
    "MapEntityCatalog",
    "MapAssetKind",
    "MapAssetProvider",
    "MapAssetResolution",
    "Pk3GeometryIndex",
    "Pk3IndexError",
    "ObjectiveGeometrySource",
    "ObjectiveMarker",
    "ObjectiveVolume",
    "SpawnPoint",
    "SurfaceType",
    "UnsupportedBspError",
    "VolumePlane",
    "entity_catalog_manifest",
    "extract_entity_catalog",
    "parse_bsp",
    "parse_bsp_file",
    "parse_entities",
]
